# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Test.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setWindowModality(QtCore.Qt.NonModal)
        mainWindow.setEnabled(True)
        mainWindow.resize(547, 425)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setBaseSize(QtCore.QSize(430, 400))
        self.mainWindowLayout = QtWidgets.QVBoxLayout(mainWindow)
        self.mainWindowLayout.setObjectName("mainWindowLayout")
        self.genReportBox = QtWidgets.QGroupBox(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genReportBox.sizePolicy().hasHeightForWidth())
        self.genReportBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.genReportBox.setFont(font)
        self.genReportBox.setCheckable(True)
        self.genReportBox.setChecked(False)
        self.genReportBox.setObjectName("genReportBox")
        self.genReportLayout = QtWidgets.QVBoxLayout(self.genReportBox)
        self.genReportLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.genReportLayout.setObjectName("genReportLayout")
        self.dateLayout = QtWidgets.QHBoxLayout()
        self.dateLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.dateLayout.setObjectName("dateLayout")
        self.startDateLabel = QtWidgets.QLabel(self.genReportBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startDateLabel.sizePolicy().hasHeightForWidth())
        self.startDateLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.startDateLabel.setFont(font)
        self.startDateLabel.setObjectName("startDateLabel")
        self.dateLayout.addWidget(self.startDateLabel)
        self.selectStartDate = QtWidgets.QDateEdit(self.genReportBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectStartDate.sizePolicy().hasHeightForWidth())
        self.selectStartDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.selectStartDate.setFont(font)
        self.selectStartDate.setFrame(True)
        self.selectStartDate.setReadOnly(False)
        self.selectStartDate.setProperty("showGroupSeparator", False)
        self.selectStartDate.setCalendarPopup(True)
        self.selectStartDate.setDate(QtCore.QDate.currentDate())
        startDate = str(QtCore.QDate.currentDate().toPyDate())
        self.selectStartDate.setObjectName("selectStartDate")
        self.dateLayout.addWidget(self.selectStartDate)
        self.endDateLabel = QtWidgets.QLabel(self.genReportBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endDateLabel.sizePolicy().hasHeightForWidth())
        self.endDateLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.endDateLabel.setFont(font)
        self.endDateLabel.setObjectName("endDateLabel")
        self.dateLayout.addWidget(self.endDateLabel)
        self.selectEndDate = QtWidgets.QDateEdit(self.genReportBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectEndDate.sizePolicy().hasHeightForWidth())
        self.selectEndDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.selectEndDate.setFont(font)
        self.selectEndDate.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.selectEndDate.setReadOnly(False)
        self.selectEndDate.setCalendarPopup(True)
        self.selectEndDate.setDate(QtCore.QDate.currentDate())
        endDate = str(QtCore.QDate.currentDate().toPyDate())
        self.selectEndDate.setObjectName("selectEndDate")
        self.dateLayout.addWidget(self.selectEndDate)
        self.genReportLayout.addLayout(self.dateLayout)
        self.locationLayout = QtWidgets.QHBoxLayout()
        self.locationLayout.setObjectName("locationLayout")
        self.locationLabel = QtWidgets.QLabel(self.genReportBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locationLabel.sizePolicy().hasHeightForWidth())
        self.locationLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.locationLabel.setFont(font)
        self.locationLabel.setObjectName("locationLabel")
        self.locationLayout.addWidget(self.locationLabel)
        self.selectLocation = QtWidgets.QComboBox(self.genReportBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectLocation.sizePolicy().hasHeightForWidth())
        self.selectLocation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.selectLocation.setFont(font)
        self.selectLocation.setEditable(False)
        self.selectLocation.setObjectName("selectLocation")
        self.selectLocation.addItem("")
        self.selectLocation.addItem("")
        self.selectLocation.addItem("")
        self.selectLocation.addItem("")
        self.locationLayout.addWidget(self.selectLocation)
        self.genReportLayout.addLayout(self.locationLayout)
        self.saveReportPathLayout = QtWidgets.QHBoxLayout()
        self.saveReportPathLayout.setObjectName("saveReportPathLayout")
        self.saveReportPathLabel = QtWidgets.QLabel(self.genReportBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveReportPathLabel.sizePolicy().hasHeightForWidth())
        self.saveReportPathLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.saveReportPathLabel.setFont(font)
        self.saveReportPathLabel.setObjectName("saveReportPathLabel")
        self.saveReportPathLayout.addWidget(self.saveReportPathLabel)
        self.selectSaveReportPath = QtWidgets.QLineEdit(self.genReportBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSaveReportPath.sizePolicy().hasHeightForWidth())
        self.selectSaveReportPath.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.selectSaveReportPath.setFont(font)
        self.selectSaveReportPath.setReadOnly(True)
        self.selectSaveReportPath.setObjectName("selectSaveReportPath")
        self.saveReportPathLayout.addWidget(self.selectSaveReportPath)
        self.browseSaveReportButton = QtWidgets.QToolButton(self.genReportBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseSaveReportButton.sizePolicy().hasHeightForWidth())
        self.browseSaveReportButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.browseSaveReportButton.setFont(font)
        self.browseSaveReportButton.setCheckable(False)
        self.browseSaveReportButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.browseSaveReportButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.browseSaveReportButton.setObjectName("browseSaveReportButton")
        self.saveReportPathLayout.addWidget(self.browseSaveReportButton)
        self.genReportLayout.addLayout(self.saveReportPathLayout)
        self.mainWindowLayout.addWidget(self.genReportBox)
        self.createSignsBox = QtWidgets.QGroupBox(mainWindow)
        self.createSignsBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createSignsBox.sizePolicy().hasHeightForWidth())
        self.createSignsBox.setSizePolicy(sizePolicy)
        self.createSignsBox.setMinimumSize(QtCore.QSize(150, 194))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.createSignsBox.setFont(font)
        self.createSignsBox.setCheckable(True)
        self.createSignsBox.setChecked(False)
        self.createSignsBox.setObjectName("createSignsBox")
        self.createSignsBoxLayout = QtWidgets.QVBoxLayout(self.createSignsBox)
        self.createSignsBoxLayout.setObjectName("createSignsBoxLayout")
        self.useExistingReportBox = QtWidgets.QGroupBox(self.createSignsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useExistingReportBox.sizePolicy().hasHeightForWidth())
        self.useExistingReportBox.setSizePolicy(sizePolicy)
        self.useExistingReportBox.setMinimumSize(QtCore.QSize(0, 76))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.useExistingReportBox.setFont(font)
        self.useExistingReportBox.setCheckable(True)
        self.useExistingReportBox.setChecked(False)
        self.useExistingReportBox.setObjectName("useExistingReportBox")
        self.useExistingReportLayout = QtWidgets.QVBoxLayout(self.useExistingReportBox)
        self.useExistingReportLayout.setObjectName("useExistingReportLayout")
        self.browseExistingReportLayout = QtWidgets.QHBoxLayout()
        self.browseExistingReportLayout.setObjectName("browseExistingReportLayout")
        self.selectExistingReportPath = QtWidgets.QLineEdit(self.useExistingReportBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectExistingReportPath.sizePolicy().hasHeightForWidth())
        self.selectExistingReportPath.setSizePolicy(sizePolicy)
        self.selectExistingReportPath.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.selectExistingReportPath.setFont(font)
        self.selectExistingReportPath.setReadOnly(True)
        self.selectExistingReportPath.setObjectName("selectExistingReportPath")
        self.browseExistingReportLayout.addWidget(self.selectExistingReportPath)
        self.browseExistingReportButton = QtWidgets.QToolButton(self.useExistingReportBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseExistingReportButton.sizePolicy().hasHeightForWidth())
        self.browseExistingReportButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.browseExistingReportButton.setFont(font)
        self.browseExistingReportButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.browseExistingReportButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.browseExistingReportButton.setAutoRaise(False)
        self.browseExistingReportButton.setArrowType(QtCore.Qt.NoArrow)
        self.browseExistingReportButton.setObjectName("browseExistingReportButton")
        self.browseExistingReportLayout.addWidget(self.browseExistingReportButton)
        self.useExistingReportLayout.addLayout(self.browseExistingReportLayout)
        self.createSignsBoxLayout.addWidget(self.useExistingReportBox)
        self.saveSignsPathLayout = QtWidgets.QHBoxLayout()
        self.saveSignsPathLayout.setObjectName("saveSignsPathLayout")
        self.saveSignsPathLabel = QtWidgets.QLabel(self.createSignsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSignsPathLabel.sizePolicy().hasHeightForWidth())
        self.saveSignsPathLabel.setSizePolicy(sizePolicy)
        self.saveSignsPathLabel.setMinimumSize(QtCore.QSize(101, 0))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.saveSignsPathLabel.setFont(font)
        self.saveSignsPathLabel.setObjectName("saveSignsPathLabel")
        self.saveSignsPathLayout.addWidget(self.saveSignsPathLabel)
        self.selectSaveSignsPath = QtWidgets.QLineEdit(self.createSignsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSaveSignsPath.sizePolicy().hasHeightForWidth())
        self.selectSaveSignsPath.setSizePolicy(sizePolicy)
        self.selectSaveSignsPath.setMinimumSize(QtCore.QSize(304, 0))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.selectSaveSignsPath.setFont(font)
        self.selectSaveSignsPath.setReadOnly(True)
        self.selectSaveSignsPath.setObjectName("selectSaveSignsPath")
        self.saveSignsPathLayout.addWidget(self.selectSaveSignsPath)
        self.browseSaveSignsButton = QtWidgets.QToolButton(self.createSignsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseSaveSignsButton.sizePolicy().hasHeightForWidth())
        self.browseSaveSignsButton.setSizePolicy(sizePolicy)
        self.browseSaveSignsButton.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.browseSaveSignsButton.setFont(font)
        self.browseSaveSignsButton.setCheckable(False)
        self.browseSaveSignsButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.browseSaveSignsButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.browseSaveSignsButton.setObjectName("browseSaveSignsButton")
        self.saveSignsPathLayout.addWidget(self.browseSaveSignsButton)
        self.createSignsBoxLayout.addLayout(self.saveSignsPathLayout)
        self.outputOptionsLayout = QtWidgets.QHBoxLayout()
        self.outputOptionsLayout.setSpacing(12)
        self.outputOptionsLayout.setObjectName("outputOptionsLayout")
        self.classroomSignsCheckbox = QtWidgets.QCheckBox(self.createSignsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classroomSignsCheckbox.sizePolicy().hasHeightForWidth())
        self.classroomSignsCheckbox.setSizePolicy(sizePolicy)
        self.classroomSignsCheckbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.classroomSignsCheckbox.setFont(font)
        self.classroomSignsCheckbox.setChecked(False)
        self.classroomSignsCheckbox.setObjectName("classroomSignsCheckbox")
        self.outputOptionsLayout.addWidget(self.classroomSignsCheckbox)
        self.dailyScheduleCheckbox = QtWidgets.QCheckBox(self.createSignsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dailyScheduleCheckbox.sizePolicy().hasHeightForWidth())
        self.dailyScheduleCheckbox.setSizePolicy(sizePolicy)
        self.dailyScheduleCheckbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.dailyScheduleCheckbox.setFont(font)
        self.dailyScheduleCheckbox.setChecked(False)
        self.dailyScheduleCheckbox.setObjectName("dailyScheduleCheckbox")
        self.outputOptionsLayout.addWidget(self.dailyScheduleCheckbox)
        self.powerpointCheckbox = QtWidgets.QCheckBox(self.createSignsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powerpointCheckbox.sizePolicy().hasHeightForWidth())
        self.powerpointCheckbox.setSizePolicy(sizePolicy)
        self.powerpointCheckbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.powerpointCheckbox.setFont(font)
        self.powerpointCheckbox.setChecked(False)
        self.powerpointCheckbox.setObjectName("powerpointCheckbox")
        self.outputOptionsLayout.addWidget(self.powerpointCheckbox)
        self.createSignsBoxLayout.addLayout(self.outputOptionsLayout)
        self.mainWindowLayout.addWidget(self.createSignsBox)
        self.startExitLayout = QtWidgets.QHBoxLayout()
        self.startExitLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.startExitLayout.setObjectName("startExitLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.startExitLayout.addItem(spacerItem)
        self.StartButton = QtWidgets.QPushButton(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartButton.sizePolicy().hasHeightForWidth())
        self.StartButton.setSizePolicy(sizePolicy)
        self.StartButton.setMinimumSize(QtCore.QSize(175, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName("StartButton")
        self.startExitLayout.addWidget(self.StartButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.startExitLayout.addItem(spacerItem1)
        self.exitButton = QtWidgets.QPushButton(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setMinimumSize(QtCore.QSize(175, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.startExitLayout.addWidget(self.exitButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.startExitLayout.addItem(spacerItem2)
        self.mainWindowLayout.addLayout(self.startExitLayout)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Auto Schedule"))
        self.genReportBox.setTitle(_translate("mainWindow", "Generate Destiny Report"))
        self.startDateLabel.setText(_translate("mainWindow", "Start Date:"))
        self.endDateLabel.setText(_translate("mainWindow", "End Date:"))
        self.locationLabel.setText(_translate("mainWindow", "Location:"))
        self.selectLocation.setItemText(0, _translate("mainWindow", "ABSW"))
        self.selectLocation.setItemText(1, _translate("mainWindow", "Belmont"))
        self.selectLocation.setItemText(2, _translate("mainWindow", "Golden Bear Center"))
        self.selectLocation.setItemText(3, _translate("mainWindow", "San Francisco Center"))
        self.saveReportPathLabel.setText(_translate("mainWindow", "Save Path:"))
        self.selectSaveReportPath.setText(_translate("mainWindow", "C:\\"))
        self.browseSaveReportButton.setText(_translate("mainWindow", "Browse"))
        self.createSignsBox.setTitle(_translate("mainWindow", "Create Signs"))
        self.useExistingReportBox.setTitle(_translate("mainWindow", "Use existing Destiny Report"))
        self.selectExistingReportPath.setText(_translate("mainWindow", "C:\\"))
        self.browseExistingReportButton.setText(_translate("mainWindow", "Browse"))
        self.saveSignsPathLabel.setText(_translate("mainWindow", "Save Path:"))
        self.selectSaveSignsPath.setText(_translate("mainWindow", "C:\\"))
        self.browseSaveSignsButton.setText(_translate("mainWindow", "Browse"))
        self.classroomSignsCheckbox.setText(_translate("mainWindow", "Classroom Sign"))
        self.dailyScheduleCheckbox.setText(_translate("mainWindow", "Daily Schedule"))
        self.powerpointCheckbox.setText(_translate("mainWindow", "PowerPoint"))
        self.StartButton.setText(_translate("mainWindow", "Start"))
        self.exitButton.setText(_translate("mainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QWidget()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

